### ISSUE TITLE
Microsoft.JSInterop.JSException: Invalid "world_en" map parameter

### ISSUE THREAD

**Issue by drma-tech** [erossini/BlazorWorldMap#2]
im using blazor .net 7.0

blazor.webassembly.js:1 Uncaught (in promise) Error: Microsoft.JSInterop.JSException: Invalid "world_en" map parameter. Please make sure you have loaded this map file in your HTML.
Error: Invalid "world_en" map parameter. Please make sure you have loaded this map file in your HTML.
    at new JQVMap (jquery.vmap.js:79:15)
    at jQuery.fn.vectorMap (jquery.vmap.js:372:19)
    at initialize (worldmap.js:9:29)
    at blazor.webassembly.js:1:3337
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (blazor.webassembly.js:1:3311)
    at Object.Gt [as invokeJSFromDotNet] (blazor.webassembly.js:1:62569)
    at Object.Ii (dotnet.7.0.7.d6ly7i5yxa.js:5:71974)
    at _mono_wasm_invoke_js_blazor (dotnet.7.0.7.d6ly7i5yxa.js:14:103886)
    at 00993286:0x1d6b6
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at PSC.Blazor.Components.WorldMap.JSWorldMapInterop.Initialize(DotNetObjectReference`1 dotNetObjectRef, ElementReference elementRef, String elementId, Object options)
   at PSC.Blazor.Components.WorldMap.WorldMap.JSAdded()
    at Object.endInvokeDotNetFromJS (blazor.webassembly.js:1:3549)
    at Object.Xt [as endInvokeDotNetFromJS] (blazor.webassembly.js:1:63263)
    at Object.Gt [as invokeJSFromDotNet] (blazor.webassembly.js:1:62760)
    at Object.Ii (dotnet.7.0.7.d6ly7i5yxa.js:5:71974)
    at _mono_wasm_invoke_js_blazor (dotnet.7.0.7.d6ly7i5yxa.js:14:103886)
    at 00993286:0x1d6b6
    at 00993286:0x1cae4
    at 00993286:0xe1d4
    at 00993286:0xd044
    at 00993286:0x1a23ad

**Comment by drma-tech** [comment]
![image](https://github.com/erossini/BlazorWorldMap/assets/12803050/c1f0839a-74ae-4ecb-b3a7-a06cb6de7bae)
for some reason, this array is empty.

**Comment by erossini** [comment]
Let me check this error
Enrico

**Comment by drma-tech** [comment]
@erossini  ok. 

I will be a very active user of this component. expect many suggestions for improvements.

**Comment by erossini** [comment]
I can replicate the error that occurs only with NET7. In the NET6 project the map is working as expected. This is interesting. Also, I noticed that the map doesn't show the button to zoom in and out.

**Comment by drma-tech** [comment]
@erossini  does not show the buttons, the pin does not appear and also the texts.

**Comment by drma-dev** [comment]
@erossini did you find out what the problem was?

**Comment by drma-dev** [comment]
@erossini

**Comment by drma-tech** [comment]
@erossini  Did you abandon the project?

**Comment by erossini** [comment]
This project is not abandon but I'm working on other components for NET8.

**Comment by drma-tech** [comment]
@erossini now we have 9.0
