### ISSUE TITLE
Error: Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'outerHTML')

### ISSUE THREAD

**Issue by drma-tech** [erossini/BlazorWorldMap#3]
blazor.webassembly.js:1 Uncaught (in promise) Error: Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'outerHTML')
TypeError: Cannot read properties of undefined (reading 'outerHTML')
    at String.<anonymous> (jquery.vmap.js:823:151)
    at Function.each (jquery-3.7.0.min.js:2:3179)
    at JQVMap.placePins (jquery.vmap.js:814:16)
    at new JQVMap (jquery.vmap.js:265:14)
    at jQuery.fn.vectorMap (jquery.vmap.js:372:19)
    at initialize (worldmap.js:9:29)
    at blazor.webassembly.js:1:3337
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (blazor.webassembly.js:1:3311)
    at Object.Gt [as invokeJSFromDotNet] (blazor.webassembly.js:1:62569)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at PSC.Blazor.Components.WorldMap.JSWorldMapInterop.Initialize(DotNetObjectReference`1 dotNetObjectRef, ElementReference elementRef, String elementId, Object options)
   at PSC.Blazor.Components.WorldMap.WorldMap.JSAdded()
    at Object.endInvokeDotNetFromJS (blazor.webassembly.js:1:3549)
    at Object.Xt [as endInvokeDotNetFromJS] (blazor.webassembly.js:1:63263)
    at Object.Gt [as invokeJSFromDotNet] (blazor.webassembly.js:1:62760)
    at Object.Ii (dotnet.7.0.7.d6ly7i5yxa.js:5:71974)
    at _mono_wasm_invoke_js_blazor (dotnet.7.0.7.d6ly7i5yxa.js:14:103886)
    at 00993286:0x1d6b6
    at 00993286:0x1cae4
    at 00993286:0xe1d4
    at 00993286:0xd044
    at 00993286:0x1a23ad

**Comment by erossini** [comment]
Let me check this one.
Enrico
